name: Docker镜像构建

- name: 缓存Docker层
  uses: actions/cache@v3
  with:
    path: /tmp/.buildx-cache
    key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}


on:
  schedule:
    - cron: '0 3 * * *' # 每天UTC时间3点运行


env: # 全局环境变量
  IMAGE_NAME: my-xmrig
  DOCKERHUB_USER: your-docker-id

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # 仅main分支触发

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 登录Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 构建并推送镜像
      uses: docker/build-push-action@v5
      with:
        context: 。
        push: true
        标签: |
          ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

- name: 发送邮件通知
  if: failure() # 仅在失败时发送
  uses: dawidd6/action-send-mail@v3
  with:
    server_address: smtp.gmail.com
    server_port: 587
    username: ${{ secrets.EMAIL_USER }}
    password: ${{ secrets.EMAIL_PASSWORD }}
    到: your-email@example.com
    subject: "构建失败: ${{ github.workflow }}"

