name: Docker镜像构建

on:
  schedule:
    - cron: '0 3 * * *' # 每天UTC时间3点运行


env: # 全局环境变量
  IMAGE_NAME: my-xmrig
  DOCKERHUB_USER: your-docker-id

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # 仅main分支触发

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 登录Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 构建并推送镜像
      uses: docker/build-push-action@v5
      with:
        context: 。
        push: true
        标签: |
          ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
