name: Docker镜像构建

on:
  push:
    branches: [ "main" ]    # main分支推送时触发
    tags: [ "v*.*.*" ]      # 标签推送时触发（如v1.2.3）
  workflow_dispatch:        # 允许手动触发

env:
  DOCKERHUB_USER: your-docker-id   # 改为你的Docker Hub ID
  IMAGE_NAME: xmrig-cpu-miner

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      # ----------------------------
      # 步骤1：检出代码
      # ----------------------------
      - name: 检出仓库
        uses: actions/checkout@v4

      # ----------------------------
      # 步骤2：登录Docker Hub
      # ----------------------------
      - name: Docker登录
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ----------------------------
      # 步骤3：构建并推送镜像
      # ----------------------------
      - name: 构建推送
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64  # 多架构支持
          push: ${{ github.event_name != 'pull_request' }} # PR时不推送
          tags: |
            ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

      # ----------------------------
      # 步骤4：验证镜像（可选）
      # ----------------------------
      - name: 运行测试
        run: |
          docker run --rm ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }} --version
